name: 'debug'
inputs:
  grep:
    description: 'what to find'
    required: true
    default: ''
outputs:
  random:
    description: "Random number"
    value: ${{ steps.random.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - id: env
      run: env | grep "${{ inputs.grep }}"
      shell: bash
    - id: random
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
